var concepts = {
'1stOT (Universal)': {'def': '', 'ref': 'UFO.html#UFO_1stOT+(Universal)_detail'},
'2ndOT': {'def': '', 'ref': 'UFO.html#UFO_2ndOT_detail'},
'3rdOT': {'def': '', 'ref': 'UFO.html#UFO_3rdOT_detail'},
'Abstract Thing': {'def': '', 'ref': 'UFO.html#UFO_Abstract+Thing_detail'},
'Action': {'def': '', 'ref': 'UFO.html#UFO_Action_detail'},
'Action Contribution': {'def': '', 'ref': 'UFO.html#UFO_Action+Contribution_detail'},
'Action Universal (Plan)': {'def': '', 'ref': 'UFO.html#UFO_Action+Universal+(Plan)_detail'},
'Activity Universal': {'def': 'Action Universal representing any generic activity in an Organization (formalized or not), which is the powertype of every Performed Activity.', 'ref': 'SPO.html#SPO_Activity+Universal_detail'},
'Adaptation Program': {'def': 'An Adaptation Program is a RRT Program that intends to satisfy at least one Change Runtime Requirement Artifact.', 'ref': 'RRO.html#RRO_Adaptation+Program_detail'},
'Adaptation Program Copy Execution': {'def': 'An Adaptation Program Copy Execution is the execution of a Loaded Adaptation Program Copy. It uses Change Runtime Requirement Artifacts as resources to triggers changes in its Loaded Target Program Copy.', 'ref': 'RRO.html#RRO_Adaptation+Program+Copy+Execution_detail'},
'Adherence Evaluation': {'def': 'Activity for objectively evaluating the adherence of processes and products to the applicable requirements, registering the identified issues.', 'ref': 'QAPO.html#QAPO_Adherence+Evaluation_detail'},
'Agent': {'def': '', 'ref': 'UFO.html#UFO_Agent_detail'},
'Agent Participation': {'def': '', 'ref': 'UFO.html#UFO_Agent+Participation_detail'},
'Allocation Unit': {'def': '', 'ref': 'EO.html#EO_Allocation+Unit_detail'},
'Analysis Result': {'def': 'Result produced by a Measurement Analysis. An Analysis Result characterizes a Measurable Entity and provides information related to a Measurement Goal.', 'ref': 'COM.html#COM_Analysis+Result_detail'},
'Analysis Result Description': {'def': 'Information Item that records the Analysis Result produced in a Software Measurement Analysis.  ', 'ref': 'RSMO.html#RSMO_Analysis+Result+Description_detail'},
'Anti-Rigid Mixin Universal': {'def': '', 'ref': 'UFO.html#UFO_Anti-Rigid+Mixin+Universal_detail'},
'Anti-Rigid Sortal Universal': {'def': '', 'ref': 'UFO.html#UFO_Anti-Rigid+Sortal+Universal_detail'},
'Appointment': {'def': '', 'ref': 'UFO.html#UFO_Appointment_detail'},
'Appointment Goal': {'def': '', 'ref': 'UFO.html#UFO_Appointment+Goal_detail'},
'Architectural Component': {'def': 'Architectural Element describing a software module as part of an Architecture.', 'ref': 'DPO.html#DPO_Architectural+Component_detail'},
'Architectural Connector': {'def': 'Architectural Element connecting two or more Components in an Architecture.', 'ref': 'DPO.html#DPO_Architectural+Connector_detail'},
'Architectural Design': {'def': 'Activity for making the high-level design choices, defining the Software Architecture and involved elements.', 'ref': 'DPO.html#DPO_Architectural+Design_detail'},
'Architectural Element': {'def': 'Model Element referring to an Architectural Component or Connector, and its Interfaces.', 'ref': 'DPO.html#DPO_Architectural+Element_detail'},
'Architecture Development': {'def': 'Activity aiming to produce the Software Architecture and specifying its Architectural Components and Connectors.', 'ref': 'DPO.html#DPO_Architecture+Development_detail'},
'Artifact': {'def': 'Object intentionally made to serve a given purpose in the context of a software Project or Organization.', 'ref': 'SPO.html#SPO_Artifact_detail'},
'Artifact CI': {'def': 'Artifact whose configuration is being managed.', 'ref': 'CMPO.html#CMPO_Artifact+CI_detail'},
'Artifact Change': {'def': 'Artifact Participation in which an existing Artifact is modified.', 'ref': 'SPO.html#SPO_Artifact+Change_detail'},
'Artifact Copy': {'def': 'Copy of an Artifact that is under version control.', 'ref': 'CMPO.html#CMPO_Artifact+Copy_detail'},
'Artifact Creation': {'def': 'Artifact Participation in which a new Artifact is created.', 'ref': 'SPO.html#SPO_Artifact+Creation_detail'},
'Artifact Evaluation': {'def': 'Activity for objectively evaluating the adherence of products and deliverables to the applicable requirements.', 'ref': 'QAPO.html#QAPO_Artifact+Evaluation_detail'},
'Artifact Participation': {'def': 'The participation of an Artifact in a Performed Activity.', 'ref': 'SPO.html#SPO_Artifact+Participation_detail'},
'Artifact Type': {'def': 'Object Kind which is the powertype of Artifact, classifying its specializations.', 'ref': 'SPO.html#SPO_Artifact+Type_detail'},
'Artifact Usage': {'def': 'Artifact Participation in which an existing Artifact is used, but not modified.', 'ref': 'SPO.html#SPO_Artifact+Usage_detail'},
'Assumption': {'def': 'Assumptions describe states-of-aaffairs in the environment of interest that the Stakeholders believe to be true, i.e., they are the propositional content of Stakeholders Beliefs. They express the belief that a specific situation exists in the environment.', 'ref': 'RSRO.html#RSRO_Assumption_detail'},
'Atomic Action': {'def': '', 'ref': 'UFO.html#UFO_Atomic+Action_detail'},
'Atomic Action Universal': {'def': '', 'ref': 'UFO.html#UFO_Atomic+Action+Universal_detail'},
'Atomic Event': {'def': '', 'ref': 'UFO.html#UFO_Atomic+Event_detail'},
'Atomic Task': {'def': 'An Atomic Task is a Task that is not decomposed in other tasks.', 'ref': 'GORO.html#GORO_Atomic+Task_detail'},
'Base Measure': {'def': 'Measure used to quantify a Directly Measurable Element.', 'ref': 'COM.html#COM_Base+Measure_detail'},
'Baseline': {'def': 'Information Item packaging a set of Configuration Items Versions at a specific time in the products life (for a product delivery or to establish a relevant point in the Project).', 'ref': 'CMPO.html#CMPO_Baseline_detail'},
'Baseline Establishment': {'def': 'Activity for establishing a Baseline embracing a planned set of Configuration Items Versions.', 'ref': 'CMPO.html#CMPO_Baseline+Establishment_detail'},
'Basic Measurement Procedure': {'def': 'Measurement Procedure applicable to a Base Measure.', 'ref': 'COM.html#COM_Basic+Measurement+Procedure_detail'},
'Belief': {'def': '', 'ref': 'UFO.html#UFO_Belief_detail'},
'Black-box Testing Technique': {'def': 'Testing technique that ignores the internal mechanism of a system or component and focuses solely on the outputs generated in response to selected inputs and execution conditions (adapted from ISO/IEC/IEEE 24765:2017 Systems and software engineering-Vocabulary)', 'ref': 'ROoST.html#ROoST_Black-box+Testing+Technique_detail'},
'Business Goal': {'def': 'Goal that expresses the intention for which strategic actions are planned and performed.', 'ref': 'RSMO.html#RSMO_Business+Goal_detail'},
'Business Role': {'def': '', 'ref': 'EO.html#EO_Business+Role_detail'},
'CASE Tool': {'def': '', 'ref': 'SPO.html#SPO_CASE+Tool_detail'},
'CR Being Solved': {'def': 'Change Request being solved after authorization.', 'ref': 'CMPO.html#CMPO_CR+Being+Solved_detail'},
'Category': {'def': '', 'ref': 'UFO.html#UFO_Category_detail'},
'Change': {'def': '', 'ref': 'UFO.html#UFO_Change_detail'},
'Change Accomplishment': {'def': 'Activity for performing the authorized changes in a set of Configuration Items under version control.', 'ref': 'CMPO.html#CMPO_Change+Accomplishment_detail'},
'Change Control': {'def': 'Activity for formally controlling the modification of Configuration Items, in a process of requesting, evaluating, changing and reviewing.', 'ref': 'CMPO.html#CMPO_Change+Control_detail'},
'Change Implementation': {'def': 'Activity for implementing the changes requested and approved for a Configuration Item.', 'ref': 'CMPO.html#CMPO_Change+Implementation_detail'},
'Change Implementer': {'def': 'Stakeholder responsible for implementing a change in Configuration Items.', 'ref': 'CMPO.html#CMPO_Change+Implementer_detail'},
'Change Request (CR)': {'def': 'Information Item describing a request for modification on a set of Configuration Items.', 'ref': 'CMPO.html#CMPO_Change+Request+(CR)_detail'},
'Change Request Closing': {'def': 'Activity for closing a reviewed and approved Change Request.', 'ref': 'CMPO.html#CMPO_Change+Request+Closing_detail'},
'Change Request Evaluator': {'def': 'Stakeholder responsible for evaluating if a Change Request should be implemented or not.', 'ref': 'CMPO.html#CMPO_Change+Request+Evaluator_detail'},
'Change Requester': {'def': 'Stakeholder responsible for requesting a change in Configuration Items.', 'ref': 'CMPO.html#CMPO_Change+Requester_detail'},
'Change Requesting': {'def': 'Activity for requesting the modification of a set of Configuration Items.', 'ref': 'CMPO.html#CMPO_Change+Requesting_detail'},
'Change Review': {'def': 'Activity for reviewing an accomplished change assuring that the modifications were made as planned.', 'ref': 'CMPO.html#CMPO_Change+Review_detail'},
'Change Reviewer': {'def': 'Stakeholder responsible for reviewing the changes in Configuration Items regarding a Change Request.', 'ref': 'CMPO.html#CMPO_Change+Reviewer_detail'},
'Change Runtime Requirement Artifact': {'def': 'Change Runtime Requirement Artifact specifies changes on the systems. behavior, in order for the software system to keep fulfilling the goals it has been designed for.', 'ref': 'RRO.html#RRO_Change+Runtime+Requirement+Artifact_detail'},
'Checkin': {'def': 'Activity for including new Versions of Configuration Items into a version control repository.', 'ref': 'CMPO.html#CMPO_Checkin_detail'},
'Checkout': {'def': 'Activity for accessing defined versions of Configuration Items from a version control repository, usually for changing purposes.', 'ref': 'CMPO.html#CMPO_Checkout_detail'},
'Closed Appointment': {'def': '', 'ref': 'UFO.html#UFO_Closed+Appointment_detail'},
'Closed CR': {'def': 'Change Request closed after solved, reviewed and approved.', 'ref': 'CMPO.html#CMPO_Closed+CR_detail'},
'Closed Commitment': {'def': '', 'ref': 'UFO.html#UFO_Closed+Commitment_detail'},
'Closed Commitment Universal': {'def': '', 'ref': 'UFO.html#UFO_Closed+Commitment+Universal_detail'},
'Code': {'def': 'Software Item representing a set of computer instructions and data definitions expressed in a programming language or in a form output by an assembler, compiler, or other translator (SEVOCAB).', 'ref': 'SwO.html#SwO_Code_detail'},
'Code Development': {'def': 'Simple Performed Activity executed for developing the software Code according to previews definitions.', 'ref': 'CPO.html#CPO_Code+Development_detail'},
'Code Documentation': {'def': 'Simple Performed Activity executed for documenting the software Code with useful information.', 'ref': 'CPO.html#CPO_Code+Documentation_detail'},
'Code Review': {'def': 'Simple Performed Activity executed for reviewing the software Code to identify errors and non-conformances.', 'ref': 'CPO.html#CPO_Code+Review_detail'},
'Code Review Report': {'def': 'Document pointing out problems identified in the Code during review activities.', 'ref': 'CPO.html#CPO_Code+Review+Report_detail'},
'Code Reviewer': {'def': 'Stakeholder responsible for reviewing the Code according to the Requirements Document and Design Document.', 'ref': 'CPO.html#CPO_Code+Reviewer_detail'},
'Code To Be Tested': {'def': 'Portion of Code (software module) to be tested by a Test Case.', 'ref': 'ROoST.html#ROoST_Code+To+Be+Tested_detail'},
'Coding': {'def': 'Composite Performed Activity executed for coordinating the Code development and documentation, according to definitions from the Requirements Document and Design Document.', 'ref': 'CPO.html#CPO_Coding_detail'},
'Coding Process': {'def': 'Specific Performed Process for conducting the activities related to software Code production.', 'ref': 'CPO.html#CPO_Coding+Process_detail'},
'Collective Social Agent': {'def': '', 'ref': 'UFO.html#UFO_Collective+Social+Agent_detail'},
'Commitment': {'def': '', 'ref': 'UFO.html#UFO_Commitment_detail'},
'Commitment Universal': {'def': '', 'ref': 'UFO.html#UFO_Commitment+Universal_detail'},
'Communicated CR': {'def': 'Change Request in the first phase, communicated.', 'ref': 'CMPO.html#CMPO_Communicated+CR_detail'},
'Complex Action': {'def': '', 'ref': 'UFO.html#UFO_Complex+Action_detail'},
'Complex Action Universal': {'def': '', 'ref': 'UFO.html#UFO_Complex+Action+Universal_detail'},
'Complex Closed Appointment': {'def': '', 'ref': 'UFO.html#UFO_Complex+Closed+Appointment_detail'},
'Complex Closed Commitment': {'def': '', 'ref': 'UFO.html#UFO_Complex+Closed+Commitment_detail'},
'Complex Commitment': {'def': '', 'ref': 'UFO.html#UFO_Complex+Commitment_detail'},
'Complex Event': {'def': '', 'ref': 'UFO.html#UFO_Complex+Event_detail'},
'Complex Goal': {'def': 'Goal that is composed by others.', 'ref': 'COM.html#COM_Complex+Goal_detail'},
'Complex Organizational Unit': {'def': '', 'ref': 'EO.html#EO_Complex+Organizational+Unit_detail'},
'Complex Standalone Formal Organization': {'def': '', 'ref': 'EO.html#EO_Complex+Standalone+Formal+Organization_detail'},
'Complex Task': {'def': 'A Complex Task is a Task that is composed in other tasks.', 'ref': 'GORO.html#GORO_Complex+Task_detail'},
'Compliance Program': {'def': 'Compliance Program is a RRT Program that intends to satisfy at least one Monitoring Runtime Requirement Artifact.', 'ref': 'RRO.html#RRO_Compliance+Program_detail'},
'Compliance Program Copy Execution': {'def': 'A Compliance Program Copy Execution is the execution of a Loaded Compliance Program Copy. It uses Monitoring Runtime Requirement Artifacts as resources to monitor Execution States.', 'ref': 'RRO.html#RRO_Compliance+Program+Copy+Execution_detail'},
'Component Design': {'def': 'Activity for refining each Architectural Component of a software.', 'ref': 'DPO.html#DPO_Component+Design_detail'},
'Component Interface Design': {'def': 'Activity for refining each Interface Specification of a software.', 'ref': 'DPO.html#DPO_Component+Interface+Design_detail'},
'Composed Quality Universal': {'def': '', 'ref': 'UFO.html#UFO_Composed+Quality+Universal_detail'},
'Composite Artifact': {'def': 'Artifact composed of other Artifacts.', 'ref': 'SPO.html#SPO_Composite+Artifact_detail'},
'Composite Intended Activity': {'def': 'Intended Activity composed of other Intended Activities.', 'ref': 'SPO.html#SPO_Composite+Intended+Activity_detail'},
'Composite Method Activity': {'def': 'Method Activity composed of other Method Activities.', 'ref': 'SPO.html#SPO_Composite+Method+Activity_detail'},
'Composite Standard Activity': {'def': 'Standard Activity composed of other Standard Activities.', 'ref': 'SPO.html#SPO_Composite+Standard+Activity_detail'},
'Conceptual Model': {'def': 'Model describing the Product Requirements under different and relevant views.', 'ref': 'RDPO.html#RDPO_Conceptual+Model_detail'},
'Conceptual Modeling': {'def': 'Composite Performed Activity executed for modeling requirements, producing Conceptual Models that provide a more comprehensive view of the problem.', 'ref': 'RDPO.html#RDPO_Conceptual+Modeling_detail'},
'Concrete Particular': {'def': '', 'ref': 'UFO.html#UFO_Concrete+Particular_detail'},
'Configuration Audit Report': {'def': 'Document reporting the results of a Quality Audit Performing, including Noncompliance and Corrective Action Registers.', 'ref': 'CMPO.html#CMPO_Configuration+Audit+Report_detail'},
'Configuration Auditing': {'def': 'Activity for verifying that a Baseline or a Deliverable Product is complete, consistent and in conformity with the specified requirements.', 'ref': 'CMPO.html#CMPO_Configuration+Auditing_detail'},
'Configuration Auditor': {'def': 'Stakeholder responsible for auditing the Configuration Management related results.', 'ref': 'CMPO.html#CMPO_Configuration+Auditor_detail'},
'Configuration Item (CI)': {'def': 'Object whose configuration is being managed.', 'ref': 'CMPO.html#CMPO_Configuration+Item+(CI)_detail'},
'Configuration Items Identification': {'def': 'Activity for identifying the Configuration Items of a Project.', 'ref': 'CMPO.html#CMPO_Configuration+Items+Identification_detail'},
'Configuration Management Plan': {'def': 'Document describing the configuration management parameters for conducting the process, including the identified Configuration Items types, the configuration systems and the planned Baselines, Configuration Audits, and Products Deliveries.', 'ref': 'CMPO.html#CMPO_Configuration+Management+Plan_detail'},
'Configuration Management Planning': {'def': 'Activity for planning the Configuration Management Process, including, among others, the Configuration Management System Establishment and the Configuration Items Identification.', 'ref': 'CMPO.html#CMPO_Configuration+Management+Planning_detail'},
'Configuration Management Process': {'def': 'Process for conducting the activities related to software configuration management, ensuring the completeness and correctness of software Configuration Items.', 'ref': 'CMPO.html#CMPO_Configuration+Management+Process_detail'},
'Configuration Management System Establishment': {'def': 'Activity for establishing the configuration management system, usually composed of version control system, a change control system and a product building system.', 'ref': 'CMPO.html#CMPO_Configuration+Management+System+Establishment_detail'},
'Configuration Manager': {'def': 'Stakeholder responsible for planning and managing the Configuration Management Process.', 'ref': 'CMPO.html#CMPO_Configuration+Manager_detail'},
'Controller': {'def': 'A Machine where a Loaded Program Copy is running (Program Copy Execution) plays the role of Controller.', 'ref': 'RRO.html#RRO_Controller_detail'},
'Corrective Action Register': {'def': 'Information Item describing an action to eliminate the cause or reduce the likelihood of recurrence of a detected nonconformity or other undesirable situation. [ISO/IEC/IEEE 24765]', 'ref': 'SPMO.html#SPMO_Corrective+Action+Register_detail'},
'Cost Estimated Activity': {'def': 'A Project Activity with cost estimated.', 'ref': 'SPMO.html#SPMO_Cost+Estimated+Activity_detail'},
'Cost Estimated Process': {'def': 'A Project Process with cost estimated.. ', 'ref': 'SPMO.html#SPMO_Cost+Estimated+Process_detail'},
'Creation': {'def': '', 'ref': 'UFO.html#UFO_Creation_detail'},
'Data Analysis': {'def': 'Activity for analyzing the selected Measured Values and producing the Analysis Result Description that records the Analysis Result.', 'ref': 'RSMO.html#RSMO_Data+Analysis_detail'},
'Data Collection': {'def': 'Activity for collecting and storing data for the Software-Related Measure indicated in the selected Software Measurement Plan Item.. ', 'ref': 'RSMO.html#RSMO_Data+Collection_detail'},
'Data Definitions': {'def': 'Information Item describing the high-level choices of how the software will manage data.', 'ref': 'DPO.html#DPO_Data+Definitions_detail'},
'Data Design': {'def': 'Activity for producing a detailed Data Model for data storage and management.', 'ref': 'DPO.html#DPO_Data+Design_detail'},
'Data High-level Design': {'def': 'Activity for establish the high-level choices regarding the software data.', 'ref': 'DPO.html#DPO_Data+High-level+Design_detail'},
'Data Model': {'def': 'Model containing the physical and logical decisions on how to manage and storage the software data.', 'ref': 'DPO.html#DPO_Data+Model_detail'},
'Delegation': {'def': '', 'ref': 'UFO.html#UFO_Delegation_detail'},
'Delegatum': {'def': '', 'ref': 'UFO.html#UFO_Delegatum_detail'},
'Deliverable': {'def': '', 'ref': 'SPMO.html#SPMO_Deliverable_detail'},
'Deliverable Product': {'def': 'Software Product ready to be delivered to the client.', 'ref': 'CMPO.html#CMPO_Deliverable+Product_detail'},
'Derivative Measurement Procedure': {'def': 'Measurement Procedure applicable to a Derived Measure.', 'ref': 'COM.html#COM_Derivative+Measurement+Procedure_detail'},
'Derived Measure': {'def': 'Measure used to quantify an Indirectly Measurable Element.', 'ref': 'COM.html#COM_Derived+Measure_detail'},
'Design Document': {'def': 'Document specifying the design of a software, by depicting the software architecture, components, interfaces and data models, as well as other information regarding the design choices and decisions.', 'ref': 'DPO.html#DPO_Design+Document_detail'},
'Design Documentation': {'def': 'Activity for registering the architectural and detailed design choices and decisions, producing a Design Document.', 'ref': 'DPO.html#DPO_Design+Documentation_detail'},
'Design Evaluation': {'def': 'Activity for evaluating a Design Document, registering the identified issues.', 'ref': 'DPO.html#DPO_Design+Evaluation_detail'},
'Design Evaluation Document': {'def': 'Document registering the issues identified in a Design Document evaluation.', 'ref': 'DPO.html#DPO_Design+Evaluation+Document_detail'},
'Design Process': {'def': 'Process for defining and specifying a solution to be implemented for a software product, considering the requirements for it. It is a refinement process starting with the software architecture, and going down to the design of its elements, interfaces, and other characteristics of a software, until achieving the design of implementation units.', 'ref': 'DPO.html#DPO_Design+Process_detail'},
'Design Time Requirement Artifact': {'def': 'Design Time Requirement Artifact is a Requirement Artifact written in natural language or other format that could not be processed by a program at runtime. It is a Requirement Artifact to be used during design time.', 'ref': 'RRO.html#RRO_Design+Time+Requirement+Artifact_detail'},
'Designer': {'def': 'Stakeholder responsible for making the Detailed Design choices for a software.', 'ref': 'DPO.html#DPO_Designer_detail'},
'Desire': {'def': '', 'ref': 'UFO.html#UFO_Desire_detail'},
'Detailed Design': {'def': 'Activity for refining a preliminary software design to the extent that it is sufficiently complete to be implemented. [ISO/IEC/IEEE 24765]', 'ref': 'DPO.html#DPO_Detailed+Design_detail'},
'Directly Measurable Element': {'def': 'Measurable Element that does not depend on others to be measured.', 'ref': 'COM.html#COM_Directly+Measurable+Element_detail'},
'Disposition': {'def': '', 'ref': 'UFO.html#UFO_Disposition_detail'},
'Document': {'def': 'Any written or pictorial, uniquely identified, information related to the software development, usually presented in a predefined format.', 'ref': 'SPO.html#SPO_Document_detail'},
'Document Template': {'def': 'Procedure aiming to establish a uniform way for preparing a Document, providing a predefined format and a defined structure for filling with the expected information.', 'ref': 'SPO.html#SPO_Document+Template_detail'},
'Document Type': {'def': 'Artifact Type which is the powertype of Document, classifying its specializations.', 'ref': 'SPO.html#SPO_Document+Type_detail'},
'Duration Estimated Activity': {'def': 'A Project Process with duration estimated.', 'ref': 'SPMO.html#SPMO_Duration+Estimated+Activity_detail'},
'Duration Estimated Process': {'def': 'A Project Process with duration estimated.', 'ref': 'SPMO.html#SPMO_Duration+Estimated+Process_detail'},
'Employment': {'def': '', 'ref': 'EO.html#EO_Employment_detail'},
'Employment Type': {'def': '', 'ref': 'EO.html#EO_Employment+Type_detail'},
'Endurant': {'def': '', 'ref': 'UFO.html#UFO_Endurant_detail'},
'Endurant Universal': {'def': '', 'ref': 'UFO.html#UFO_Endurant+Universal_detail'},
'Entity': {'def': '', 'ref': 'UFO.html#UFO_Entity_detail'},
'Estimated Activity': {'def': 'A Project Activity with scope, cost, duration and time estimated.', 'ref': 'SPMO.html#SPMO_Estimated+Activity_detail'},
'Estimated Process': {'def': 'A Project Process with cost, duration and time estimated.', 'ref': 'SPMO.html#SPMO_Estimated+Process_detail'},
'Estimated Stakeholder Allocation': {'def': '', 'ref': 'SPMO.html#SPMO_Estimated+Stakeholder+Allocation_detail'},
'Evaluated Artifact': {'def': 'Artifact objectively evaluated.', 'ref': 'QAPO.html#QAPO_Evaluated+Artifact_detail'},
'Evaluated CR': {'def': 'Change Request evaluated and set as authorized or rejected.', 'ref': 'CMPO.html#CMPO_Evaluated+CR_detail'},
'Evaluated Process': {'def': 'Process objectively evaluated.', 'ref': 'QAPO.html#QAPO_Evaluated+Process_detail'},
'Evaluation Report': {'def': 'Document describing the evaluation results and identified issues.', 'ref': 'QAPO.html#QAPO_Evaluation+Report_detail'},
'Event': {'def': '', 'ref': 'UFO.html#UFO_Event_detail'},
'Event Universal': {'def': '', 'ref': 'UFO.html#UFO_Event+Universal_detail'},
'Expression': {'def': '', 'ref': 'UFO.html#UFO_Expression_detail'},
'Externally Dependent Moment': {'def': '', 'ref': 'UFO.html#UFO_Externally+Dependent+Moment_detail'},
'Formal Organization': {'def': '', 'ref': 'EO.html#EO_Formal+Organization_detail'},
'Formal Organization Employer': {'def': '', 'ref': 'EO.html#EO_Formal+Organization+Employer_detail'},
'Formal Organization Member Type': {'def': '', 'ref': 'EO.html#EO_Formal+Organization+Member+Type_detail'},
'Formal Organization Type': {'def': '', 'ref': 'EO.html#EO_Formal+Organization+Type_detail'},
'Formal Relation': {'def': '', 'ref': 'UFO.html#UFO_Formal+Relation_detail'},
'Fulfilled': {'def': '', 'ref': 'UFO.html#UFO_Fulfilled_detail'},
'Function': {'def': '', 'ref': 'UFO.html#UFO_Function_detail'},
'Function': {'def': '', 'ref': 'UFO.html#UFO_Function_detail'},
'Function Universal': {'def': '', 'ref': 'UFO.html#UFO_Function+Universal_detail'},
'Functional Requirement': {'def': 'Requirement defining a function to be available in the product being built.', 'ref': 'RSRO.html#RSRO_Functional+Requirement_detail'},
'General Intended Process': {'def': 'Intended Process that is composed of Specific Intended Processes, allowing an Organization or Project to define sub-processes that are part of a complete Intended Process.', 'ref': 'SPO.html#SPO_General+Intended+Process_detail'},
'General Project Process': {'def': '', 'ref': 'SPO.html#SPO_General+Project+Process_detail'},
'General Standard Process': {'def': 'Standard Process that is composed of Specific Standard Processes, allowing an Organization to establish sub-processes that are part of a complete Standard Process.', 'ref': 'SPO.html#SPO_General+Standard+Process_detail'},
'Goal': {'def': '', 'ref': 'UFO.html#UFO_Goal_detail'},
'Hardgoal': {'def': 'Hardgoal is a proposition that is objectively satisfied by a given set of situations.', 'ref': 'GORO.html#GORO_Hardgoal_detail'},
'Hardware Equipment': {'def': 'Physical Object used for running software programs or to support some related action.', 'ref': 'SPO.html#SPO_Hardware+Equipment_detail'},
'Hardware Resource': {'def': 'Hardware Equipment when used as Resource of some process activity.', 'ref': 'SPO.html#SPO_Hardware+Resource_detail'},
'Hardware Resource Participation': {'def': 'The participation of a Hardware Equipment as a Resource in a Performed Activity.', 'ref': 'SPO.html#SPO_Hardware+Resource+Participation_detail'},
'Hardware Type': {'def': 'Object Kind which is the powertype of Hardware Equipment, classifying its specializations.', 'ref': 'SPO.html#SPO_Hardware+Type_detail'},
'High Order Universal': {'def': '', 'ref': 'UFO.html#UFO_High+Order+Universal_detail'},
'Higher-Order Object Kind': {'def': '', 'ref': 'UFO.html#UFO_Higher-Order+Object+Kind_detail'},
'Human Resource': {'def': '', 'ref': 'EO.html#EO_Human+Resource_detail'},
'Human Resource Role': {'def': '', 'ref': 'EO.html#EO_Human+Resource+Role_detail'},
'Hybrid Standard Process': {'def': 'Standard Process established to be performed in the context of a Project or Organization.', 'ref': 'SPO.html#SPO_Hybrid+Standard+Process_detail'},
'Incident Management Tool': {'def': 'Software product that manages and maintains lists of issues as needed by an organization (adapted from Wikipedia).', 'ref': 'ROoST.html#ROoST_Incident+Management+Tool_detail'},
'Incident Report': {'def': 'Report describing the occurrence, nature, and status of an incident (adapted from ISO/IEC/IEEE 29119-1:2013 Software and systems engineering--Software testing--Part 1: Concepts and definitions, 4.18).', 'ref': 'ROoST.html#ROoST_Incident+Report_detail'},
'Indicator': {'def': 'Measure directly used to indicate the achievement of Measurement Goals.', 'ref': 'COM.html#COM_Indicator_detail'},
'Indirectly Measurable Element': {'def': 'Measurable Element that depends on others (its sub-elements) to be measured.', 'ref': 'COM.html#COM_Indirectly+Measurable+Element_detail'},
'Individual': {'def': '', 'ref': 'UFO.html#UFO_Individual_detail'},
'Information Item': {'def': 'Relevant information for human use, produced or used by Performed Activity.', 'ref': 'SPO.html#SPO_Information+Item_detail'},
'Information Need': {'def': 'Information Needs are identified from Measurement Goals and determine which information have to be met by Measures in order to monitor the achievement of the related Measurement Goal.', 'ref': 'COM.html#COM_Information+Need_detail'},
'Information Need Description': {'def': 'Information Item that documents the description of an Information Need.', 'ref': 'RSMO.html#RSMO_Information+Need+Description_detail'},
'Information Needs Identification': {'def': 'Activity for identifying and recording the Information Needs to be included in the Software Measurement Plan. Information Needs are identified from the established Software Measurement Goals.', 'ref': 'RSMO.html#RSMO_Information+Needs+Identification_detail'},
'Integration Testing': {'def': 'Level-based Testing focusing on larger components, ensuring that a collection of units functions as desired.', 'ref': 'ROoST.html#ROoST_Integration+Testing_detail'},
'Intended Activity': {'def': 'Intention (Internal Commitment) representing the activity defined to be performed as part of an Intended Process, by a defined role, potentially consuming and producing artifacts, using resources and adopting procedures.', 'ref': 'SPO.html#SPO_Intended+Activity_detail'},
'Intended Process': {'def': 'Intention (Internal Commitment) representing the process defined to be performed in a specific project or organizational area, considering its particularities.', 'ref': 'SPO.html#SPO_Intended+Process_detail'},
'Intention': {'def': '', 'ref': 'UFO.html#UFO_Intention_detail'},
'Intentional Moment': {'def': '', 'ref': 'UFO.html#UFO_Intentional+Moment_detail'},
'Interface High-level Design': {'def': 'Activity for specifying the Interfaces between Architectural Components and with external elements (users or other systems).', 'ref': 'DPO.html#DPO_Interface+High-level+Design_detail'},
'Interface Specification': {'def': 'Information Item describing an internal or external interface of a software architecture.', 'ref': 'DPO.html#DPO_Interface+Specification_detail'},
'Internal Closed Commitment Universal': {'def': '', 'ref': 'UFO.html#UFO_Internal+Closed+Commitment+Universal_detail'},
'Internal Commitment Universal': {'def': '', 'ref': 'UFO.html#UFO_Internal+Commitment+Universal_detail'},
'Interval MeaRefDimension': {'def': '', 'ref': 'UFO.html#UFO_Interval+MeaRefDimension_detail'},
'Interval Scale': {'def': 'Scale in which it is possible to quantify the distance between its Scale Values and there is not a value to represent nonentity (absolute zero). In an Interval Scale, although it is possible to quantify the distance between Scale Values, it is not possible to establish other relations between them.', 'ref': 'COM.html#COM_Interval+Scale_detail'},
'Intrinsic Moment': {'def': '', 'ref': 'UFO.html#UFO_Intrinsic+Moment_detail'},
'Intrisic Moment Universal': {'def': '', 'ref': 'UFO.html#UFO_Intrisic+Moment+Universal_detail'},
'Item': {'def': 'Object whose configuration may be managed.', 'ref': 'CMPO.html#CMPO_Item_detail'},
'Job Plan': {'def': '', 'ref': 'EO.html#EO_Job+Plan_detail'},
'Kind': {'def': '', 'ref': 'UFO.html#UFO_Kind_detail'},
'Level-based Testing': {'def': 'Composite Performed Activity consisting of testing activities and classified by the different levels they can be performed.', 'ref': 'ROoST.html#ROoST_Level-based+Testing_detail'},
'Loaded Adaptation Program Copy': {'def': 'Loaded Adaptation Program Copy is the materialization of an Adaptation Program.', 'ref': 'RRO.html#RRO_Loaded+Adaptation+Program+Copy_detail'},
'Loaded Compliance Program Copy': {'def': 'Loaded Compliance Program Copy is the materialization of a Compliance Program.', 'ref': 'RRO.html#RRO_Loaded+Compliance+Program+Copy_detail'},
'Loaded Program Copy': {'def': 'Loaded Program Copy is the materialization of a Program, inhering in a Machine.', 'ref': 'RRO.html#RRO_Loaded+Program+Copy_detail'},
'Loaded RRT Program Copy': {'def': 'Loaded RRT Program Copy is the materialization of a RRT Program.', 'ref': 'RRO.html#RRO_Loaded+RRT+Program+Copy_detail'},
'Loaded Target Program Copy': {'def': 'Loaded Target Program Copy is the materialization of a Target Program.', 'ref': 'RRO.html#RRO_Loaded+Target+Program+Copy_detail'},
'Machine': {'def': 'Machine is a hardware equipament able to run programs.', 'ref': 'RRO.html#RRO_Machine_detail'},
'Machine Code': {'def': 'Computer instructions and data definitions expressed in a form output by an assembler, compiler, or other translator, which can be recognized by the processing unit of a computer machine.', 'ref': 'SwO.html#SwO_Machine+Code_detail'},
'Material Relation': {'def': '', 'ref': 'UFO.html#UFO_Material+Relation_detail'},
'Measurable Element': {'def': 'Measurable property that characterizes a Measurable Entity Type.', 'ref': 'COM.html#COM_Measurable+Element_detail'},
'Measurable Entity': {'def': 'Anything that can be measured.', 'ref': 'COM.html#COM_Measurable+Entity_detail'},
'Measurable Entity Type': {'def': 'Type of entities that can be measured.', 'ref': 'COM.html#COM_Measurable+Entity+Type_detail'},
'Measurable Quality Universal': {'def': '', 'ref': 'UFO.html#UFO_Measurable+Quality+Universal_detail'},
'Measurable Software-Related Entity': {'def': 'Measurable Entity related to software.', 'ref': 'RSMO.html#RSMO_Measurable+Software-Related+Entity_detail'},
'Measurable Software-Related Entity Type': {'def': 'Type of Measurable Entities related to software.', 'ref': 'RSMO.html#RSMO_Measurable+Software-Related+Entity+Type_detail'},
'Measure': {'def': 'Function used to associate a value (Measured Value) to a Measurable Element of a Measurable Entity. Measures quantify Measurable Elements and characterize Measurable Entity Types.', 'ref': 'COM.html#COM_Measure_detail'},
'Measure Description': {'def': 'Information Item that documents the description of  a Software-Related Measure.', 'ref': 'RSMO.html#RSMO_Measure+Description_detail'},
'Measure Unit': {'def': 'Unit in which measures can be expressed.', 'ref': 'COM.html#COM_Measure+Unit_detail'},
'Measured Value': {'def': 'Value obtained in a Measurement.', 'ref': 'COM.html#COM_Measured+Value_detail'},
'Measured Value Description': {'def': 'Information Item that records a Measured Value.', 'ref': 'RSMO.html#RSMO_Measured+Value+Description_detail'},
'Measurement': {'def': 'Action that measures a Measurable Element of a Measurable Entity by applying a Measure and adopting a Measurement Procedure to obtain a Measured Value. A Measurement is performed based on a Measurement Planning Item.', 'ref': 'COM.html#COM_Measurement_detail'},
'Measurement Analysis': {'def': 'Action that analyzes Measure Values collected for Measures aiming to characterize a Measurable Entity and provide information related to a Measurement Goal.', 'ref': 'COM.html#COM_Measurement+Analysis_detail'},
'Measurement Analysis Procedure': {'def': 'Procedure applied to analyze Measured Values obtained for a Software-Related Measure. ', 'ref': 'RSMO.html#RSMO_Measurement+Analysis+Procedure_detail'},
'Measurement Analyst': {'def': 'Role played by the Stakeholder in charge of Software Measurement Analysis.', 'ref': 'RSMO.html#RSMO_Measurement+Analyst_detail'},
'Measurement Context': {'def': 'Situation in which a Software Measurement Execution was performed.', 'ref': 'RSMO.html#RSMO_Measurement+Context_detail'},
'Measurement Executor': {'def': 'Role played by the Stakeholder in charge of Software Measurement Execution. It does not include automated measurement (by tools).', 'ref': 'RSMO.html#RSMO_Measurement+Executor_detail'},
'Measurement Formula': {'def': 'Formula that quantifies relations between Measures from which a Derived Measure is obtained.', 'ref': 'COM.html#COM_Measurement+Formula_detail'},
'Measurement Goal': {'def': 'Goal that can be used to drive the identification of the Measures needed to provide information in a certain context. Measurement Goals are established based on more general Goals.', 'ref': 'COM.html#COM_Measurement+Goal_detail'},
'Measurement Goals Establishment': {'def': 'Activity for establishing and recording the Software Measurement Goals to be included in the Software Measurement Plan.. ', 'ref': 'RSMO.html#RSMO_Measurement+Goals+Establishment_detail'},
'Measurement Manager': {'def': 'Role played by the Stakeholder in charge of Software Measurement Planning.', 'ref': 'RSMO.html#RSMO_Measurement+Manager_detail'},
'Measurement Plan Item Selection': {'def': 'Activity for selecting the Software Measurement Plan Item to be used to guide the Software Measurement Execution. The selected Software Measurement Plan Item indicates the Software-Related Measured to be applied in the Software Measurement Execution and the Operational Definition of Measure to be considered.. ', 'ref': 'RSMO.html#RSMO_Measurement+Plan+Item+Selection_detail'},
'Measurement Planning': {'def': 'Action that plans the measurement, i.e., determines the Measurement Goals to be monitored, the Information Needs to be considered, the Measures to be collected to meet the Information Needs and the Measurement Procedures to be applied. ', 'ref': 'COM.html#COM_Measurement+Planning_detail'},
'Measurement Planning Item': {'def': 'Social Object produced during Measurement Planning. A Measurement Planning Item specifies a Measurement Goal to be monitored, an Information Need to be considered, a Measure to be used to meet the Information Need and a Measurement Procedure to be applied to collect data for the Measure. Several Measurement Planning Items can be produced during Measurement Planning.', 'ref': 'COM.html#COM_Measurement+Planning+Item_detail'},
'Measurement Planning Start': {'def': 'Activity for defining the Software Measurement Plan structure, its initial information (e.g., organization to which it was defined and elaboration date) and starting its elaboration.. ', 'ref': 'RSMO.html#RSMO_Measurement+Planning+Start_detail'},
'Measurement Procedure': {'def': 'Procedure applicable to a Measure and that describe the steps to be carried out to collect data for it.', 'ref': 'COM.html#COM_Measurement+Procedure_detail'},
'Measurement Quality Domain': {'def': '', 'ref': 'UFO.html#UFO_Measurement+Quality+Domain_detail'},
'Measurement Quality Region': {'def': '', 'ref': 'UFO.html#UFO_Measurement+Quality+Region_detail'},
'Measurement Quality Structure': {'def': '', 'ref': 'UFO.html#UFO_Measurement+Quality+Structure_detail'},
'Measurement Reference Dimension': {'def': '', 'ref': 'UFO.html#UFO_Measurement+Reference+Dimension_detail'},
'Measurement Reference Region': {'def': '', 'ref': 'UFO.html#UFO_Measurement+Reference+Region_detail'},
'Measurement Reference Structure': {'def': '', 'ref': 'UFO.html#UFO_Measurement+Reference+Structure_detail'},
'Measurement Result Reporting': {'def': 'Activity for communicating the Analysis Result Description to the relevant Stakeholders.. ', 'ref': 'RSMO.html#RSMO_Measurement+Result+Reporting_detail'},
'Measures Identification': {'def': 'Activity for identifying and recording the Software-Related Measures to be included in the Software Measurement Plan. Software-Related Measures are identified from Information Needs in the sense that Measures must meet the identified Information Needs.', 'ref': 'RSMO.html#RSMO_Measures+Identification_detail'},
'Mental Moment': {'def': '', 'ref': 'UFO.html#UFO_Mental+Moment_detail'},
'Method': {'def': 'Systematic Procedure defining a workflow of activities (a set of steps) and heuristics to perform one or more activities.', 'ref': 'SPO.html#SPO_Method_detail'},
'Method Activity': {'def': 'Action type representing one of the steps of a Method Workflow.', 'ref': 'SPO.html#SPO_Method+Activity_detail'},
'Method Workflow': {'def': 'Complex Action type denoting a set of steps (Method Activities) to be used when a Method is adopted.', 'ref': 'SPO.html#SPO_Method+Workflow_detail'},
'Mixin Universal': {'def': '', 'ref': 'UFO.html#UFO_Mixin+Universal_detail'},
'Mode': {'def': '', 'ref': 'UFO.html#UFO_Mode_detail'},
'Mode Universal': {'def': '', 'ref': 'UFO.html#UFO_Mode+Universal_detail'},
'Model': {'def': 'A representation (abstraction) of a process or system from a particular perspective.', 'ref': 'SPO.html#SPO_Model_detail'},
'Model-based Testing Technique': {'def': 'Testing technique in which the test cases are derived from a model that describes the system under test.', 'ref': 'ROoST.html#ROoST_Model-based+Testing+Technique_detail'},
'Moment': {'def': '', 'ref': 'UFO.html#UFO_Moment_detail'},
'Moment Universal': {'def': '', 'ref': 'UFO.html#UFO_Moment+Universal_detail'},
'Monitoring Runtime Requirement Artifact': {'def': 'Monitoring Runtime Requirement Artifact defines the criteria for verifying if a requirement is being satisfied or not at. runtime.', 'ref': 'RRO.html#RRO_Monitoring+Runtime+Requirement+Artifact_detail'},
'Multi Formal Organization': {'def': '', 'ref': 'EO.html#EO_Multi+Formal+Organization_detail'},
'Mutation Testing Technique': {'def': 'Testing technique in which two or more program mutations are executed using the same test cases to evaluate the ability of the test cases to detect differences in the mutations (ISO/IEC/IEEE 24765:2017 Systems and software engineering-Vocabulary)', 'ref': 'ROoST.html#ROoST_Mutation+Testing+Technique_detail'},
'Non-Functional Requirement': {'def': 'Requirement defining criteria or capabilities for the product.', 'ref': 'RSRO.html#RSRO_Non-Functional+Requirement_detail'},
'Noncompliance Closing': {'def': 'Activity for finishing a noncompliance once it is satisfactorily solved.', 'ref': 'QAPO.html#QAPO_Noncompliance+Closing_detail'},
'Noncompliance Control': {'def': 'Activity for managing the registered noncompliances until their effective resolution.', 'ref': 'QAPO.html#QAPO_Noncompliance+Control_detail'},
'Noncompliance Identification': {'def': 'Activity for registering the noncompliances identified in processes and artifacts.', 'ref': 'QAPO.html#QAPO_Noncompliance+Identification_detail'},
'Noncompliance Register': {'def': 'Information Item describing a noncompliance (a failure or refusal to conform to an applicable requirement) in a process or artifact, and related information to solve it.', 'ref': 'QAPO.html#QAPO_Noncompliance+Register_detail'},
'Noncompliance Resolution': {'def': 'Activity for analyzing a noncompliance, planning and executing the applicable corrective actions to its resolution.', 'ref': 'QAPO.html#QAPO_Noncompliance+Resolution_detail'},
'Noncompliance Responsible': {'def': 'Stakeholder responsible for solving a noncompliance.', 'ref': 'QAPO.html#QAPO_Noncompliance+Responsible_detail'},
'Normative Description': {'def': '', 'ref': 'UFO.html#UFO_Normative+Description_detail'},
'OU Assignment': {'def': '', 'ref': 'EO.html#EO_OU+Assignment_detail'},
'OU Assignment Type': {'def': '', 'ref': 'EO.html#EO_OU+Assignment+Type_detail'},
'OU Member': {'def': '', 'ref': 'EO.html#EO_OU+Member_detail'},
'Object': {'def': '', 'ref': 'UFO.html#UFO_Object_detail'},
'Object Kind': {'def': '', 'ref': 'UFO.html#UFO_Object+Kind_detail'},
'Object Participation': {'def': '', 'ref': 'UFO.html#UFO_Object+Participation_detail'},
'Observable State': {'def': 'Observable State is a situation resulting from the execution of a program copy. It involves qualities and quality values (qualia) of the Machine in which the Loaded Program Copy inheres, as well as of entities residing in that Machine (including the Loaded Program Copy itself).', 'ref': 'RRO.html#RRO_Observable+State_detail'},
'Operational Definition of Measure': {'def': 'Information Item that specifies information regarding data collection and analysis of a Software-Related Measure. An Operational Definition of Measure indicates: Measurement Procedure, Measurement Periodicity, Measurement Moment, Measurement Responsible, Measurement Analysis Procedure, Measurement Analysis Periodicity, Measurement Analysis Moment, and Measurement Analysis Responsible.. ', 'ref': 'RSMO.html#RSMO_Operational+Definition+of+Measure_detail'},
'Operational Definition of Measure Establishment': {'def': 'Activity for establishing the Operational Definitions of Measures for the identified Software-Related Measures.. ', 'ref': 'RSMO.html#RSMO_Operational+Definition+of+Measure+Establishment_detail'},
'Ordinal MeaRefDimension': {'def': '', 'ref': 'UFO.html#UFO_Ordinal+MeaRefDimension_detail'},
'Ordinal Scale': {'def': 'Scale whose Scale Values can be mapped to a certain order or ranking.', 'ref': 'COM.html#COM_Ordinal+Scale_detail'},
'Organization': {'def': 'Same as UFO::Organization.. A Social Agent involving people and other agents and facilities with an arrangement of responsibilities, authorities and relationships.', 'ref': 'EO.html#EO_Organization_detail'},
'Organization Stakeholder': {'def': 'Organization interested or affected by the process activities or results.', 'ref': 'SPO.html#SPO_Organization+Stakeholder_detail'},
'Organizational Intended Process': {'def': 'Intended Process defined to be performed in the context of an Organization, regardless of specific Projects.', 'ref': 'SPO.html#SPO_Organizational+Intended+Process_detail'},
'Organizational Role': {'def': 'A Social Role, recognized by the Organization, assigned to Agents when they are hired, included in a team, allocated or participating in activities.', 'ref': 'EO.html#EO_Organizational+Role_detail'},
'Organizational Standard Process': {'def': 'Standard Process established to be performed in the context of an Organization, regardless of specific Projects.', 'ref': 'SPO.html#SPO_Organizational+Standard+Process_detail'},
'Organizational Team': {'def': '', 'ref': 'EO.html#EO_Organizational+Team_detail'},
'Organizational Unit': {'def': '', 'ref': 'EO.html#EO_Organizational+Unit_detail'},
'Organizational Unit Type': {'def': '', 'ref': 'EO.html#EO_Organizational+Unit+Type_detail'},
'Participation': {'def': '', 'ref': 'UFO.html#UFO_Participation_detail'},
'Participation Universal': {'def': '', 'ref': 'UFO.html#UFO_Participation+Universal_detail'},
'Performed Activity': {'def': 'Action performed, in a specific Time Interval, by a Stakeholder, potentially producing and consuming Artifacts, as part of a Specific Performed Process.', 'ref': 'SPO.html#SPO_Performed+Activity_detail'},
'Performed Composite Activity': {'def': 'Performed Activity composed of other Performed Activities.', 'ref': 'SPO.html#SPO_Performed+Composite+Activity_detail'},
'Performed General Process': {'def': 'The overall Performed Process executed in a specific Project or Organization, which is necessarily composed of Specific Performed Processes.', 'ref': 'SPO.html#SPO_Performed+General+Process_detail'},
'Performed Organizational Process': {'def': 'Performed Process executed in the context of an Organization, regardless of specific Projects.', 'ref': 'SPO.html#SPO_Performed+Organizational+Process_detail'},
'Performed Process': {'def': 'Complex Action, composed of other processes or activities, performed in a specific Time Interval, for reaching a goal in a Project or Organization.', 'ref': 'SPO.html#SPO_Performed+Process_detail'},
'Performed Project Activity': {'def': '', 'ref': 'SPO.html#SPO_Performed+Project+Activity_detail'},
'Performed Project Process': {'def': 'Performed Process executed within a Project.', 'ref': 'SPO.html#SPO_Performed+Project+Process_detail'},
'Performed Simple Activity': {'def': 'Performed Activity that is not further decomposed into other Performed Activities.', 'ref': 'SPO.html#SPO_Performed+Simple+Activity_detail'},
'Performed Specific Process': {'def': 'Performed Process that is part of the General Performed Process of a Project or Organization, necessarily composed of at least two Performed Activities.', 'ref': 'SPO.html#SPO_Performed+Specific+Process_detail'},
'Periodicity': {'def': '', 'ref': 'RSMO.html#RSMO_Periodicity_detail'},
'Person': {'def': 'Same as UFO::Human Agent. A human Physical Agent.', 'ref': 'UFO.html#UFO_Person_detail'},
'Person Stakeholder': {'def': 'Person interested or affected by the process activities or their results.', 'ref': 'SPO.html#SPO_Person+Stakeholder_detail'},
'Phase': {'def': '', 'ref': 'UFO.html#UFO_Phase_detail'},
'Phasemixin': {'def': '', 'ref': 'UFO.html#UFO_Phasemixin_detail'},
'Physical Agent': {'def': '', 'ref': 'UFO.html#UFO_Physical+Agent_detail'},
'Physical Object': {'def': '', 'ref': 'UFO.html#UFO_Physical+Object_detail'},
'Plan Description': {'def': '', 'ref': 'UFO.html#UFO_Plan+Description_detail'},
'Planning Item Documentation': {'def': 'Activity for documenting Measurement Planning Items. Each Measurement Planning Item includes a Software Measurement Goal Description, an Information Need Description, a Software-Related Measure and an Operational Definition of Measure. Measurement Planning Items produced during the Software Measurement Analysis are part of the Software Measurement Plan produced in that activity.. ', 'ref': 'RSMO.html#RSMO_Planning+Item+Documentation_detail'},
'Practical Result': {'def': '', 'ref': 'SPMO.html#SPMO_Practical+Result_detail'},
'Procedure': {'def': 'Normative Description prescribing a defined way for performing process activities.', 'ref': 'SPO.html#SPO_Procedure_detail'},
'Procedure Participation': {'def': 'The participation of a Procedure in a Performed Activity.', 'ref': 'SPO.html#SPO_Procedure+Participation_detail'},
'Process Evaluation': {'def': 'Activity for objectively evaluating the adherence of processes and activities to the applicable requirements.', 'ref': 'QAPO.html#QAPO_Process+Evaluation_detail'},
'Process Universal': {'def': 'Complex Action Universal representing any generic process in an Organization (formalized or not), which is the powertype of every Performed Process.', 'ref': 'SPO.html#SPO_Process+Universal_detail'},
'Processual Role': {'def': '', 'ref': 'UFO.html#UFO_Processual+Role_detail'},
'Product Quality Requirement': {'def': 'Non-Functional Requirement referring to a Quality Characteristic of the software product.', 'ref': 'RSRO.html#RSRO_Product+Quality+Requirement_detail'},
'Program': {'def': 'Software Item which aims at producing a certain result through execution on a computer, in a particular way, given by the Program Specification. A Program is constituted by code, but it is not identical to code. Code can be changed without altering the identity of its program, which is anchored to the programs essential property: its intended specification (Program Specification).', 'ref': 'SwO.html#SwO_Program_detail'},
'Program Copy Execution': {'def': 'Program Copy Execution is an Event representing the execution of the Loaded Program Copy running in a Machine. In other words, the Program Copy Execution is the event of the physical manifestation of the dispositions (represented as the complex disposition Loaded Program Copy) that inhere in the Machine.', 'ref': 'RRO.html#RRO_Program+Copy+Execution_detail'},
'Program Specification': {'def': 'A document that describes the purpose (structure and functions) of a program in sufficient detail to permit coding and to facilitate maintenance.', 'ref': 'SwO.html#SwO_Program+Specification_detail'},
'Programmer': {'def': 'Stakeholder with programming skills responsible for producing and documenting the software Code.', 'ref': 'CPO.html#CPO_Programmer_detail'},
'Programming Language': {'def': 'A language used to express computer programs.', 'ref': 'SwO.html#SwO_Programming+Language_detail'},
'Project': {'def': 'A Social Object as a temporary endeavor undertaken to create a unique product, service, or result.', 'ref': 'EO.html#EO_Project_detail'},
'Project Activity': {'def': 'Intended Activity defined to be performed within a Project, and thus that is part of a Project Process.', 'ref': 'SPO.html#SPO_Project+Activity_detail'},
'Project Manager': {'def': 'Stakeholder responsible for managing a Project.', 'ref': 'SPMO.html#SPMO_Project+Manager_detail'},
'Project Plan': {'def': 'Document describing the planning of a Project, to be used as the basis for project management.', 'ref': 'SPMO.html#SPMO_Project+Plan_detail'},
'Project Process': {'def': 'Intended Process defined to be performed within a Project.', 'ref': 'SPO.html#SPO_Project+Process_detail'},
'Project Stakeholder': {'def': 'Stakeholder interested in a particular Project.', 'ref': 'SPO.html#SPO_Project+Stakeholder_detail'},
'Project Standard Process': {'def': 'A Standard Process established to be performed within a Project.', 'ref': 'SPO.html#SPO_Project+Standard+Process_detail'},
'Project Team': {'def': '', 'ref': 'EO.html#EO_Project+Team_detail'},
'Proposition': {'def': '', 'ref': 'UFO.html#UFO_Proposition_detail'},
'Quality': {'def': '', 'ref': 'UFO.html#UFO_Quality_detail'},
'Quality Assurance Plan': {'def': 'Document registering the planed quality assurance activities, processes and artifacts to be evaluated and involved personnel.', 'ref': 'QAPO.html#QAPO_Quality+Assurance+Plan_detail'},
'Quality Assurance Planning': {'def': 'Activity for planning the quality assurance activities, resulting in a Quality Assurance Plan.', 'ref': 'QAPO.html#QAPO_Quality+Assurance+Planning_detail'},
'Quality Assurance Process': {'def': 'Process for conducting the activities related to software quality assurance, assessing and assuring adherence of the performed processes and produced artifacts to the applicable requirements.', 'ref': 'QAPO.html#QAPO_Quality+Assurance+Process_detail'},
'Quality Auditor': {'def': 'Stakeholder responsible for conducting objective evaluations.', 'ref': 'QAPO.html#QAPO_Quality+Auditor_detail'},
'Quality Characteristic': {'def': 'Quality Universal denoting the types of quality characteristics expected in a software.', 'ref': 'RSRO.html#RSRO_Quality+Characteristic_detail'},
'Quality Region': {'def': '', 'ref': 'UFO.html#UFO_Quality+Region_detail'},
'Quality Structure': {'def': '', 'ref': 'UFO.html#UFO_Quality+Structure_detail'},
'Quality Universal': {'def': '', 'ref': 'UFO.html#UFO_Quality+Universal_detail'},
'RRT Program': {'def': 'An RRT Program is a Program that is built intending to satisfy at least one Runtime Requirement Artifact.', 'ref': 'RRO.html#RRO_RRT+Program_detail'},
'RRT Program Copy Execution': {'def': 'An RRT Program Copy Execution is the execution of a Loaded RRT Program Copy. It uses Runtime Requirement Artifacts as resources.', 'ref': 'RRO.html#RRO_RRT+Program+Copy+Execution_detail'},
'Rational MeaRefDimension': {'def': '', 'ref': 'UFO.html#UFO_Rational+MeaRefDimension_detail'},
'Rational Scale': {'def': 'Scale in which it is possible to quantify the distance between its Scale Values, there is a value to represent nonentity (absolute zero) and it is possible to establish relations between Scale Values.', 'ref': 'COM.html#COM_Rational+Scale_detail'},
'Reference Structure': {'def': '', 'ref': 'UFO.html#UFO_Reference+Structure_detail'},
'Relation': {'def': '', 'ref': 'UFO.html#UFO_Relation_detail'},
'Relator': {'def': '', 'ref': 'UFO.html#UFO_Relator_detail'},
'Relator Universal': {'def': '', 'ref': 'UFO.html#UFO_Relator+Universal_detail'},
'Release Management and Delivery': {'def': 'Activity for managing the building, releasing and delivering of the products to be delivered to clients.', 'ref': 'CMPO.html#CMPO_Release+Management+and+Delivery_detail'},
'Request Evaluation': {'def': 'Activity for evaluating the Change Request for a set of Configuration Items, authorizing or rejecting it.', 'ref': 'CMPO.html#CMPO_Request+Evaluation_detail'},
'Requirement': {'def': 'Goal to be achieved, representing a condition or capacity needed for the system users for solving a problem.', 'ref': 'RSRO.html#RSRO_Requirement_detail'},
'Requirement': {'def': 'A Goal in the scope of a specific problem, that describes environmental conditions to be achieved through a desired solution resulting in satisfaction of the underlying strategic goals. In GORE, these goals can be refined by decomposing them into sub-goals, as well as by defining them by means of alternative goals.', 'ref': 'GORO.html#GORO_Requirement_detail'},
'Requirement Artifact': {'def': 'Information Item describing a Requirement.', 'ref': 'RSRO.html#RSRO_Requirement+Artifact_detail'},
'Requirements Agreement': {'def': 'Information Item representing the agreement achieved by the Stakeholders, regarding the Requirements for the product.', 'ref': 'RDPO.html#RDPO_Requirements+Agreement_detail'},
'Requirements Development Process': {'def': 'Specific Performed Process for establishing and developing the requirements for a system or software.', 'ref': 'RDPO.html#RDPO_Requirements+Development+Process_detail'},
'Requirements Document': {'def': 'Document composed of Documented Requirements and related information, as a basis for other technical software processes, including maintenance.', 'ref': 'RSRO.html#RSRO_Requirements+Document_detail'},
'Requirements Documentation': {'def': 'Composite Performed Activity executed for recording Documented Requirements and related Conceptual Models in Requirements Documents, assuring proper recording and management of them during and after the project.', 'ref': 'RDPO.html#RDPO_Requirements+Documentation_detail'},
'Requirements Elicitation': {'def': 'Composite Performed Activity executed for identifying requirements from the Stakeholders and other sources, and documenting them.', 'ref': 'RDPO.html#RDPO_Requirements+Elicitation_detail'},
'Requirements Engineer': {'def': 'Stakeholder responsible for conducting the requirements development activities.', 'ref': 'RSRO.html#RSRO_Requirements+Engineer_detail'},
'Requirements Evaluation Document': {'def': 'Document pointing out problems identified in Documented Requirements and Conceptual Models registered in a Requirements Document.', 'ref': 'RDPO.html#RDPO_Requirements+Evaluation+Document_detail'},
'Requirements Negotiation and Prioritization': {'def': 'Composite Performed Activity executed to solve problems in the requirements and to reach an agreement on the set of requirements to be considered in the Project and their priorities.', 'ref': 'RDPO.html#RDPO_Requirements+Negotiation+and+Prioritization_detail'},
'Requirements Reviewer': {'def': 'Stakeholder responsible for conducting reviews in requirements artifacts.', 'ref': 'RDPO.html#RDPO_Requirements+Reviewer_detail'},
'Requirements Stakeholder': {'def': 'Stakeholder that provides needs and expectations for the product.', 'ref': 'RSRO.html#RSRO_Requirements+Stakeholder_detail'},
'Requirements Verification and Validation': {'def': 'Composite Performed Activity executed for evaluating Documented Requirements and Conceptual Models registered in Requirements Documents, and for recording the identified problems.', 'ref': 'RDPO.html#RDPO_Requirements+Verification+and+Validation_detail'},
'Resource': {'def': 'Software Product or Hardware Equipment when used by a process activity.', 'ref': 'SPO.html#SPO_Resource_detail'},
'Reviewed CR': {'def': 'Change Request reviewed to check if the modifications done are correct.', 'ref': 'CMPO.html#CMPO_Reviewed+CR_detail'},
'Rigid Mixin Universal': {'def': '', 'ref': 'UFO.html#UFO_Rigid+Mixin+Universal_detail'},
'Rigid Sortal Universal': {'def': '', 'ref': 'UFO.html#UFO_Rigid+Sortal+Universal_detail'},
'Role': {'def': '', 'ref': 'UFO.html#UFO_Role_detail'},
'Rolemixin': {'def': '', 'ref': 'UFO.html#UFO_Rolemixin_detail'},
'Runtime Requirement Artifact': {'def': 'Runtime Requirement Artifact is a Requirement Artifact written in a computational file that could be processed by a program at runtime (RRT Program Copy Execution).', 'ref': 'RRO.html#RRO_Runtime+Requirement+Artifact_detail'},
'Scale': {'def': 'Delimitates the space of values possible to be associated by a Measure to a Measurable Element.', 'ref': 'COM.html#COM_Scale_detail'},
'Scale Value': {'def': 'Value that compose a Scale.', 'ref': 'COM.html#COM_Scale+Value_detail'},
'Scheduled Activity': {'def': 'An Intended Activity defining the time interval it is planned to be performed.', 'ref': 'SPO.html#SPO_Scheduled+Activity_detail'},
'Scheduled Process': {'def': 'An Intended Process defining the Time Interval it is planned to be performed.', 'ref': 'SPO.html#SPO_Scheduled+Process_detail'},
'Scientific Measurement Domain': {'def': '', 'ref': 'UFO.html#UFO_Scientific+Measurement+Domain_detail'},
'Scope Estimated Activity': {'def': 'A Project Activity with its scope in the project defined in terms of the work packages that it shall produce.', 'ref': 'SPMO.html#SPMO_Scope+Estimated+Activity_detail'},
'Selection of Data for Analysis': {'def': 'Activity for selecting the Measured Values of the selected Software-Related Measures to be analyzed in the Software Measurement Analysis.. ', 'ref': 'RSMO.html#RSMO_Selection+of+Data+for+Analysis_detail'},
'Selection of Entity for Measurement': {'def': 'Activity for selecting the Software-Related Measurable Entity to be measured in the Software Measurement Execution. The selected entity type must be the Software-Related Measurable Entity Type indicated in the Operational Definition of Measure defined in the selected Software Measurement Plan Item.. ', 'ref': 'RSMO.html#RSMO_Selection+of+Entity+for+Measurement_detail'},
'Selection of Measurement Goals for Analysis': {'def': 'Activity for selecting the Software Measurement Goal to be monitored by using information provided by the Software Measurement Analysis.  . ', 'ref': 'RSMO.html#RSMO_Selection+of+Measurement+Goals+for+Analysis_detail'},
'Selection of Measures for Analysis': {'def': 'Activity for selecting, among the Software-Related Measures related to the selected Software Measurement Goal the ones to be analyzed in the Software Measurement Analysis.. ', 'ref': 'RSMO.html#RSMO_Selection+of+Measures+for+Analysis_detail'},
'Self Appointment': {'def': '', 'ref': 'UFO.html#UFO_Self+Appointment_detail'},
'Set': {'def': '', 'ref': 'UFO.html#UFO_Set_detail'},
'Simple Artifact': {'def': 'Artifact that is not decomposed into other Artifacts.', 'ref': 'SPO.html#SPO_Simple+Artifact_detail'},
'Simple Goal': {'def': 'Goal that is not composed by others.', 'ref': 'COM.html#COM_Simple+Goal_detail'},
'Simple Intended Activity': {'def': 'Intended Activity that is not further decomposed into other Intended Activities.', 'ref': 'SPO.html#SPO_Simple+Intended+Activity_detail'},
'Simple Method Activity': {'def': 'Method Activity that is not further decomposed into other Method Activities.', 'ref': 'SPO.html#SPO_Simple+Method+Activity_detail'},
'Simple Organizational Unit': {'def': '', 'ref': 'EO.html#EO_Simple+Organizational+Unit_detail'},
'Simple Quality Universal': {'def': '', 'ref': 'UFO.html#UFO_Simple+Quality+Universal_detail'},
'Simple Standalone Formal Organization': {'def': '', 'ref': 'EO.html#EO_Simple+Standalone+Formal+Organization_detail'},
'Simple Standard Activity': {'def': 'Standard Activity that is not further decomposed into other Standard Activities.', 'ref': 'SPO.html#SPO_Simple+Standard+Activity_detail'},
'Situation': {'def': '', 'ref': 'UFO.html#UFO_Situation_detail'},
'Social Agent': {'def': '', 'ref': 'UFO.html#UFO_Social+Agent_detail'},
'Social Appointment': {'def': '', 'ref': 'UFO.html#UFO_Social+Appointment_detail'},
'Social Commitment': {'def': '', 'ref': 'UFO.html#UFO_Social+Commitment_detail'},
'Social Moment': {'def': '', 'ref': 'UFO.html#UFO_Social+Moment_detail'},
'Social Object': {'def': '', 'ref': 'UFO.html#UFO_Social+Object_detail'},
'Social Relator': {'def': '', 'ref': 'UFO.html#UFO_Social+Relator_detail'},
'Social Role': {'def': '', 'ref': 'UFO.html#UFO_Social+Role_detail'},
'Softgoal': {'def': 'Softgoal is an initial and temporary vague expression of a goal not suficiently defined yet. It refers to a vague quality region whose exact boundaries are unknown. Thus it is not  possible to determine a priori the set of situations that satisfies the softgoal. Its satisfiability is usually related to an agents judgement.', 'ref': 'GORO.html#GORO_Softgoal_detail'},
'Software Architect': {'def': 'Stakeholder responsible for designing the Software Architecture.', 'ref': 'DPO.html#DPO_Software+Architect_detail'},
'Software Architecture': {'def': 'Model describing the fundamental structures of a software, including its components, how they are connected, and its internal and external interfaces.', 'ref': 'DPO.html#DPO_Software+Architecture_detail'},
'Software Function': {'def': 'Software Functions are functional dispositions that constitute the complex disposition Loaded Program Copy. Each Software Function is an instance of a Software Function Universal. When the software development process is accomplished correctly, the Software Functions that constitute the Loaded Program Copy are instances of the exact Software Function Universals described by the Program Specification and successfully implemented by the Program.', 'ref': 'RRO.html#RRO_Software+Function_detail'},
'Software Function Universal': {'def': 'Function Universal denoting the types of functions expected in a software.', 'ref': 'RSRO.html#RSRO_Software+Function+Universal_detail'},
'Software Goal': {'def': 'Goal that expresses the intention for which software-related actions are planned and performed. Software Goals are based on Business Goals.', 'ref': 'RSMO.html#RSMO_Software+Goal_detail'},
'Software Item': {'def': 'Piece of software, produced during the software process, not considered a complete Software Product, but an intermediary result.', 'ref': 'SPO.html#SPO_Software+Item_detail'},
'Software Measurement Analysis': {'def': 'Activity for analyzing Measured Values collected for Software-Related Measures aiming to characterize a Software-Related Measurable Entity and provide information related to a Software Measurement Goal. ', 'ref': 'RSMO.html#RSMO_Software+Measurement+Analysis_detail'},
'Software Measurement Execution': {'def': 'Activity for measuring a Software-Related Measurable Entity by applying a Software-Related Measure and obtaining a Measured Value.', 'ref': 'RSMO.html#RSMO_Software+Measurement+Execution_detail'},
'Software Measurement Goal': {'def': 'Measurement Goal related to software. Software Measurement Goals are based on Business Goals or Software Goals.', 'ref': 'RSMO.html#RSMO_Software+Measurement+Goal_detail'},
'Software Measurement Goal Description': {'def': 'Information Item that documents the description of a Software Measurement Goal.', 'ref': 'RSMO.html#RSMO_Software+Measurement+Goal+Description_detail'},
'Software Measurement Plan': {'def': 'Document produced during Software Measurement Planning. It is composed of Software Measurement Planning Items.', 'ref': 'RSMO.html#RSMO_Software+Measurement+Plan_detail'},
'Software Measurement Planning': {'def': 'Activity for planning the software measurement, i.e., for determining the Software Measurement Goals to be monitored, the Information Needs to be considered, the Software-Related Measures to be collected to meet the Information Needs and the Operational Definition of Measure to be considered. ', 'ref': 'RSMO.html#RSMO_Software+Measurement+Planning_detail'},
'Software Measurement Planning Item': {'def': 'Measurement Planning Item related to software. It is an Information Item produced during Software Measurement Planning and it is composed of a Software Measurement Goal Description, an Information Need Description, a Measure Description and an Operational Definition of Measure.', 'ref': 'RSMO.html#RSMO_Software+Measurement+Planning+Item_detail'},
'Software Measurement Process': {'def': 'The Software Measurement Process is a Process with the purpose of collecting, analyzing, and reporting data relating to the products developed and the processes used to develop them, aiming to support effective processes management and objectively demonstrate products quality.', 'ref': 'RSMO.html#RSMO_Software+Measurement+Process_detail'},
'Software Organization': {'def': '', 'ref': 'SPO.html#SPO_Software+Organization_detail'},
'Software Product': {'def': 'One or more computer programs together with any accompanying auxiliary items, such as documentation, delivered under a single name, ready for use.', 'ref': 'SPO.html#SPO_Software+Product_detail'},
'Software Product Type': {'def': 'Artifact Type which is the powertype of Software Product, classifying its specializations.', 'ref': 'SPO.html#SPO_Software+Product+Type_detail'},
'Software Project': {'def': 'A Project related to software development or maintenance.', 'ref': 'SPO.html#SPO_Software+Project_detail'},
'Software Project Measurement Plan': {'def': 'A Software Measurement Plan defined for a Project.', 'ref': 'RSMO.html#RSMO_Software+Project+Measurement+Plan_detail'},
'Software Resource': {'def': 'Software Product when used as Resource of some process activity.', 'ref': 'SPO.html#SPO_Software+Resource_detail'},
'Software Resource Participation': {'def': 'The participation of a Software Product as Resource in a Performed Activity.', 'ref': 'SPO.html#SPO_Software+Resource+Participation_detail'},
'Software System': {'def': 'Software Item that aims at satisfying a specification (System Specification), concerning a desired change in a data structure inside a computer, abstracting away from the behavior.', 'ref': 'SwO.html#SwO_Software+System_detail'},
'Software-Related Measure': {'def': 'Measure used to quantify Measurable Elements of Measurable Software-Related Entities.', 'ref': 'RSMO.html#RSMO_Software-Related+Measure_detail'},
'Solved CR': {'def': 'Change Request solved through the Change Implementation.', 'ref': 'CMPO.html#CMPO_Solved+CR_detail'},
'Sortal Universal': {'def': '', 'ref': 'UFO.html#UFO_Sortal+Universal_detail'},
'Source Code': {'def': 'A well-formed sequence of computer instructions and data definitions expressed in a programming language, in a form suitable for input to an assembler, compiler,. or other translator.', 'ref': 'SwO.html#SwO_Source+Code_detail'},
'Specific Intended Process': {'def': 'Intended Process that is part of the General Intended Process of a Project or Organization, necessarily composed of at least two Intended Activities.', 'ref': 'SPO.html#SPO_Specific+Intended+Process_detail'},
'Specific Project Process': {'def': '', 'ref': 'SPO.html#SPO_Specific+Project+Process_detail'},
'Specific Standard Process': {'def': 'Standard Process that can be part of a General Standard Process of a Project or Organization, necessarily composed of at least two Standard Activities.', 'ref': 'SPO.html#SPO_Specific+Standard+Process_detail'},
'Stakeholder': {'def': 'Agent (Person, Team or Organization) interested or affected by the process activities or results.', 'ref': 'SPO.html#SPO_Stakeholder_detail'},
'Stakeholder Allocation': {'def': 'Social Relator representing a Stakeholder allocated to perform a Scheduled Activity acting an Organizational Role.', 'ref': 'SPO.html#SPO_Stakeholder+Allocation_detail'},
'Stakeholder Belief': {'def': 'The belief of Requirements Stakeholders regarding the environment of interest that are described in terms of Assumptions.', 'ref': 'RSRO.html#RSRO_Stakeholder+Belief_detail'},
'Stakeholder Intention': {'def': 'The intention of Requirements Stakeholders that defines requirements to be achieved.', 'ref': 'RSRO.html#RSRO_Stakeholder+Intention_detail'},
'Stakeholder Main Participation': {'def': 'The participation of a Stakeholder as the main responsible for a Performed Activity, playing an Organizational Role.', 'ref': 'SPO.html#SPO_Stakeholder+Main+Participation_detail'},
'Stakeholder Participation': {'def': 'The participation of a Stakeholder in a Performed Activity, playing an Organizational Role.', 'ref': 'SPO.html#SPO_Stakeholder+Participation_detail'},
'Standalone Formal Organization': {'def': '', 'ref': 'EO.html#EO_Standalone+Formal+Organization_detail'},
'Standard Activity': {'def': 'Action Universal representing a generic activity institutionalized as part of a Standard Process in an Organization, establishing general information such as dependence on other activities, types of artifacts created, changed and used, required software and hardware resources, adopted procedures, and roles to perform it.', 'ref': 'SPO.html#SPO_Standard+Activity_detail'},
'Standard Process': {'def': 'Complex Action Universal representing a generic process institutionalized in an Organization, establishing basic requirements for Intended Processes to be performed in that Organization or in its Projects.', 'ref': 'SPO.html#SPO_Standard+Process_detail'},
'Standard Process Definition Document': {'def': 'Plan Description, recognized by an Organization, which describes a set of Standard Processes.', 'ref': 'SPO.html#SPO_Standard+Process+Definition+Document_detail'},
'Stub': {'def': 'Skeletal or special-purpose test code substituting a software module, used to test a module that calls or is otherwise dependent on it (adapted from ISO/IEC/IEEE 24765:2017 Systems and software engineering - Vocabulary)', 'ref': 'ROoST.html#ROoST_Stub_detail'},
'Subkind': {'def': '', 'ref': 'UFO.html#UFO_Subkind_detail'},
'Substantial': {'def': '', 'ref': 'UFO.html#UFO_Substantial_detail'},
'Substantial Universal': {'def': '', 'ref': 'UFO.html#UFO_Substantial+Universal_detail'},
'System Specification': {'def': '', 'ref': 'SwO.html#SwO_System+Specification_detail'},
'System Testing': {'def': 'Level-based Testing focusing on the behavior of the entire system, ensuring that it is in conformance with its requirements.', 'ref': 'ROoST.html#ROoST_System+Testing_detail'},
'Target Execution State': {'def': 'Execution State is the Observable State resulting from the Target Program Copy Execution, which is monitored by some Compliance Program Copy Executions.', 'ref': 'RRO.html#RRO_Target+Execution+State_detail'},
'Target Program': {'def': 'Target Program is the role a Program plays when it is the targer of a RRT Program, i.e., the RRT Program are built to act over (monitor/change) the Target Program.', 'ref': 'RRO.html#RRO_Target+Program_detail'},
'Target Program Copy Execution': {'def': 'A Target Program Copy Execution is the execution of a Loaded Target Program Copy. It brings about to an Execution State.', 'ref': 'RRO.html#RRO_Target+Program+Copy+Execution_detail'},
'Task': {'def': 'A Task is a plan to achieve a goal.', 'ref': 'GORO.html#GORO_Task_detail'},
'Team': {'def': 'Social Agent representing a group of people with a defined purpose.', 'ref': 'EO.html#EO_Team_detail'},
'Team Member': {'def': '', 'ref': 'EO.html#EO_Team+Member_detail'},
'Team Membership': {'def': '', 'ref': 'EO.html#EO_Team+Membership_detail'},
'Team Purpose': {'def': '', 'ref': 'EO.html#EO_Team+Purpose_detail'},
'Team Stakeholder': {'def': 'Team interested or affected by the process activities or results.', 'ref': 'SPO.html#SPO_Team+Stakeholder_detail'},
'Technique': {'def': 'Procedure that provides heuristics to perform an activity (but in a less rigid and detailed way than a method, since it does not prescribe a set of activities).', 'ref': 'SPO.html#SPO_Technique_detail'},
'Test Analysis Report': {'def': 'Document containing the analysis of Test Results and how they succeed.', 'ref': 'ROoST.html#ROoST_Test+Analysis+Report_detail'},
'Test Case': {'def': 'Document containing the input data, expected results, steps and general conditions for testing some situation regarding a Code To Be Tested.', 'ref': 'ROoST.html#ROoST_Test+Case_detail'},
'Test Case Actual Result': {'def': 'The actual result obtained from the execution of a test case.', 'ref': 'ROoST.html#ROoST_Test+Case+Actual+Result_detail'},
'Test Case Design': {'def': 'Simple Performed Activity for designing the Test Cases to be executed, supported by input artifacts.', 'ref': 'ROoST.html#ROoST_Test+Case+Design_detail'},
'Test Case Design Input': {'def': 'Some Artifact defined as an input for the Test Case Design.', 'ref': 'ROoST.html#ROoST_Test+Case+Design+Input_detail'},
'Test Case Designer': {'def': 'Stakeholder responsible for designing test cases and analysing test results.', 'ref': 'ROoST.html#ROoST_Test+Case+Designer_detail'},
'Test Case Expected Result': {'def': 'The result expected from the execution of a test case.', 'ref': 'ROoST.html#ROoST_Test+Case+Expected+Result_detail'},
'Test Code': {'def': 'Code produced for implementing a Test Case.', 'ref': 'ROoST.html#ROoST_Test+Code_detail'},
'Test Coding': {'def': 'Simple Performed Activity for implementing the Test Cases as Code artifacts (Test Code) to be used during Test Execution.', 'ref': 'ROoST.html#ROoST_Test+Coding_detail'},
'Test Driver': {'def': 'Software item used to invoke a module under test and, often, provide test inputs, control and monitor execution, and report test results (adapted from ISO/IEC/IEEE 24765:2017 Systems and software engineering-Vocabulary).', 'ref': 'ROoST.html#ROoST_Test+Driver_detail'},
'Test Execution': {'def': 'Simple Performed Activity for effectively executing the Test Cases, by running the Test Code and producing the Test Results.', 'ref': 'ROoST.html#ROoST_Test+Execution_detail'},
'Test Hardware Resource': {'def': 'Hardware Resource that comprises the Testing Environment of a Project.', 'ref': 'ROoST.html#ROoST_Test+Hardware+Resource_detail'},
'Test Incident Report': {'def': 'Report describing any event that occurs during the testing process which requires investigation (adapted from ISO/IEC/IEEE 24765:2017 Systems and software engineering-Vocabulary)', 'ref': 'ROoST.html#ROoST_Test+Incident+Report_detail'},
'Test Input': {'def': 'Descriptions of the parameters and values to be used in a test case, in order to produce an expected result.', 'ref': 'ROoST.html#ROoST_Test+Input_detail'},
'Test Management Tool': {'def': 'Software Product used to store information on how testing is to be done, plan testing activities and report the status of testing activities (adpated from Wikipedia).', 'ref': 'ROoST.html#ROoST_Test+Management+Tool_detail'},
'Test Manager': {'def': 'Stakeholder responsible for planning and managing the testing activities.', 'ref': 'ROoST.html#ROoST_Test+Manager_detail'},
'Test Plan': {'def': 'Document describing how the tests should be performed, providing a roadmap for the testing activities.', 'ref': 'ROoST.html#ROoST_Test+Plan_detail'},
'Test Planning': {'def': 'Composite Performed Activity for planning how the testing activities should be performed, and documenting it in a Test Plan.', 'ref': 'ROoST.html#ROoST_Test+Planning_detail'},
'Test Result': {'def': 'Document containing the actual results and identified issues relative to a Test Case execution.', 'ref': 'ROoST.html#ROoST_Test+Result_detail'},
'Test Result Analysis': {'def': 'Simple Performed Activity for analyzing Test Results to determine whether or not tests have been successful in identifying defects.', 'ref': 'ROoST.html#ROoST_Test+Result+Analysis_detail'},
'Test Script': {'def': 'Short program written in a programming language used to test part of the functionality of a software system. Test scripts written as a short program can either be written using a special automated functional GUI test tool or in a well-known programming language (Wikipedia).', 'ref': 'ROoST.html#ROoST_Test+Script_detail'},
'Test Software Resource': {'def': 'Software Resource that comprises the Testing Environment of a Project.', 'ref': 'ROoST.html#ROoST_Test+Software+Resource_detail'},
'Test Suite': {'def': 'A collection of test cases that are intended to be used to test a software program to show that it has some specified set of behaviours (Wikipedia).', 'ref': 'ROoST.html#ROoST_Test+Suite_detail'},
'Tester': {'def': 'Stakeholder responsible for coding and executing test cases.', 'ref': 'ROoST.html#ROoST_Tester_detail'},
'Testing Environment': {'def': 'The set of resources (Hardware and Software Resources) that are used to perform testing activities of a Project.', 'ref': 'ROoST.html#ROoST_Testing+Environment_detail'},
'Testing Level': {'def': 'Levels in which testing activities are performed, such as Unit, Integration and System testing.', 'ref': 'ROoST.html#ROoST_Testing+Level_detail'},
'Testing Process': {'def': 'Specific Performed Process for planning and executing the dynamic testing activities for the software in development.', 'ref': 'ROoST.html#ROoST_Testing+Process_detail'},
'Testing Technique': {'def': 'Technique for designing test cases. It can be Black-box, White-box, Model-based or Mutation testing techniques, among others.', 'ref': 'ROoST.html#ROoST_Testing+Technique_detail'},
'Testing Technique Type': {'def': 'Major types of testing techniques such as black-box, white-box, model-based and mutation testing techniques.', 'ref': 'ROoST.html#ROoST_Testing+Technique+Type_detail'},
'Time Interval': {'def': '', 'ref': 'UFO.html#UFO_Time+Interval_detail'},
'Tracked Activity': {'def': '', 'ref': 'SPMO.html#SPMO_Tracked+Activity_detail'},
'Tracked Process': {'def': '', 'ref': 'SPMO.html#SPMO_Tracked+Process_detail'},
'Tracked Stakeholder Participation': {'def': '', 'ref': 'SPMO.html#SPMO_Tracked+Stakeholder+Participation_detail'},
'Unfulfilled': {'def': '', 'ref': 'UFO.html#UFO_Unfulfilled_detail'},
'Unit': {'def': '', 'ref': 'UFO.html#UFO_Unit_detail'},
'Unit Testing': {'def': 'Level-based Testing focusing on the unit or the individual components that have been developed, ensuring that the unit functions correctly in isolation.', 'ref': 'ROoST.html#ROoST_Unit+Testing_detail'},
'Usage': {'def': '', 'ref': 'UFO.html#UFO_Usage_detail'},
'User Interface Design': {'def': 'Activity for specifying the User Interfaces in detail.', 'ref': 'DPO.html#DPO_User+Interface+Design_detail'},
'User Interface Specification': {'def': 'Interface Specification focusing on the human-computer interaction.', 'ref': 'DPO.html#DPO_User+Interface+Specification_detail'},
'Version': {'def': 'Each identified release of a Configuration Item submitted to a version control repository.', 'ref': 'CMPO.html#CMPO_Version_detail'},
'White-box Testing Technique': {'def': 'Testing Technique in which the tests are derived from an examination of the structure of the code to be tested (adapted from ISO/IEC/IEEE 29119-1:2013 Software and systems engineering--Software testing--Part 1: Concepts and definitions)', 'ref': 'ROoST.html#ROoST_White-box+Testing+Technique_detail'},
'Work Package': {'def': '', 'ref': 'SPMO.html#SPMO_Work+Package_detail'},
'xOrganization': {'def': '', 'ref': 'UFO.html#UFO_xOrganization_detail'},
};